name: 🐞 Bug
description: File a bug
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please [search the issues](https://github.com/mastodon/mastodon-ios/issues) to see if an issue already exists for the bug you encountered. Please check also the [closed issues](https://github.com/mastodon/mastodon-ios/issues?q=is%3Aissue+is%3Aclosed). 
    options:
    - label: I have searched the issues (both open and closed)
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Tap '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      You can check the version and build number in the bottom of in-app settings.
      examples:
        - **Device**: iPhone X
        - **OS**: iOS 15.3
        - **Version**: `2023.15`
        - **Build**: 103
    value: |
        - Device:
        - OS:
        - Version:
        - Build:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      The server domain? Post links? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or video or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
