name: CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - feature-*
      - issue/*
      - issue-*
  pull_request:
    branches:
      - develop

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: CI build
    runs-on: macos-13
    steps:
      - name: Repository
        uses: actions/checkout@v2
      - name: Setup Build Environment
        env:
          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh
      - name: Build App
        run: bundle exec fastlane ios build_only
