name: Build for Develop

on: 
  push:
    branches:
    - develop
    - release*
    - ci-test
    - feature/setup_emerge_tools

jobs:
  build:
    name: Build
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup
        env: 
          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh

      - name: Install codemagic-cli-tools
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip3 install codemagic-cli-tools
      - run: |
          codemagic-cli-tools --version || true

      - name: Setup Env variables
        env: 
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Base SHA is $BASE_SHA"
          echo "PR number is $PULL_NUMBER"

      # - name: Build
      #   env: 
      #     ENV_APP_ID: ${{ secrets.APP_ID }}
      #     ENV_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     ENV_API_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      #     ENV_API_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      #     ENV_API_PRIVATE_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_KEY_BASE64 }}
      #   run: exec ./.github/scripts/build-release.sh

      # - name: Copy Link Maps

      - name: Upload to Emerge Tools
        env: 
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_TOOLS_API_KEY }}
        run: bundle exec fastlane app_size