name: Update localization files

on:
  push:
    branches:
    - l10n_develop
    - auto-update-l10n

permissions:
  contents: write

jobs:
  l10n:
    name: Update localization files
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        env:
          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh
      - name: Update localization files
        run: exec ./update_localization.sh
      - name: Check for changes
        id: changes
        run: |
          git status --porcelain
          if git diff --quiet; then
            echo "No changes to commit. Skipping push."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Avoid infinite loops
        if: steps.changes.outputs.changes == 'true'
        run: |
          if git log -1 --pretty=%B | grep -q "Auto-update generated files"; then
            echo "This commit was generated by the localization workflow. Exiting."
            echo "::error::Localization files changed again after auto-update, failing now to avoid infinite loop."
            exit 1
          fi
      - name: Commit and push changes
        if: steps.changes.outputs.changes == 'true'
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Auto-update generated files"
