name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
    - feature-*
    - issue/*
    - issue-*
  pull_request:
    branches:
    - develop

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: CI build
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        env: 
          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh
      - name: build
        run: exec ./.github/scripts/build.sh
