name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
    - feature-*
    - issue/*
    - issue-*
  pull_request:
    branches:
    - develop

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: CI build
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        env: 
          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh
      - name: build
        run: exec ./.github/scripts/build.sh
  emerge_tools:
    name: Upload to Emerge Tools
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        env: 
          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: exec ./.github/scripts/setup.sh
      - name: Setup Env variables
        env: 
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Base SHA is $BASE_SHA"
          echo "PR number is $PULL_NUMBER"
      - name: archive
        env:
          SCHEME: Debug
        run: exec ./.github/scripts/archive.sh
      - name: Upload to Emerge Tools
        env: 
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_TOOLS_API_KEY }}
          SCHEME: Debug
        run: bundle exec fastlane app_size
